#!/bin/bash -ex

sudo apt update
sudo apt install -y \
     build-essential \
     busybox-static \
     libffi-dev \
     libssl-dev \
     python3-dev \
     tox

lxc config set core.trust_password password
lxc config set core.https_address "[::]"

# force generation of client certificate to an address that doesn't work (http)
# generate an openssl certificate and key for the remote not verified test
config_dir="$HOME/.config/lxc"
mkdir -p "$config_dir"
openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:secp384r1 -sha384 \
        -keyout "$config_dir/client.key" -out "$config_dir/client.crt" \
        -nodes -subj "/CN=example.com" -days 3650

if ! lxc storage show default >/dev/null 2>&1; then
    lxc storage create default dir
    lxc profile device add default root disk path=/ pool=default
fi

# finally run the integration tests
tox -e integration
