#!/bin/bash -ex

sudo apt update
sudo apt install -y \
     build-essential \
     busybox-static \
     libffi-dev \
     libssl-dev \
     python3-dev \
     tox

lxc config set core.trust_password password
lxc config set core.https_address "[::]"

if ! lxc storage show default >/dev/null 2>&1; then
    lxc storage create default dir
    lxc profile device add default root disk path=/ pool=default
fi

# finally run the integration tests
tox -e integration
