#!/bin/bash -ex

sudo apt update
sudo apt install -y \
     build-essential \
     libffi-dev \
     libssl-dev \
     python3-dev \
     tox

lxc config set core.trust_password password
lxc config set core.https_address "[::]"

# force generation of client certificate to an address that doesn't work (http)
# generate an openssl certificate and key for the remote not verified test
config_dir="$HOME/.config/lxc"
mkdir -p "$config_dir"
openssl genrsa 2048 > "$config_dir/client.key"
chmod 400 "$config_dir/client.key"

openssl req -new -x509 -nodes -sha1 -days 365 \
        -key "$config_dir/client.key" -out "$config_dir/client.crt" \
        -subj="/C=UK/ST=London/L=London/O=OrgName/OU=Test/CN=example.com"

lxc storage create default dir
lxc profile device add default root disk path=/ pool=default

# finally run the integration tests
tox -e integration
