#!/bin/bash
set -ex

_dir="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"
_release=$(lsb_release -c | cut -f 2)

if [[ "${_release}" == "bionic" ]]; then
	echo "Running Bionic (18:04) integration tests"
	exec ${_dir}/run_integration_tests-18-04
else
	echo "Running Xenial (16:04) integration tests"
	exec ${_dir}/run_integration_tests-16-04
fi
