name: Commits
on:
  - pull_request

permissions:
  contents: read

jobs:
  target-branch:
    permissions:
      contents: none
    name: Branch target
    runs-on: ubuntu-22.04
    steps:
    - name: Check branch target
      env:
        TARGET: ${{ github.event.pull_request.base.ref }}
      run: |
        set -x
        [ "${TARGET}" = "main" ] && exit 0

        echo "Invalid branch target: ${TARGET}"
        exit 1
