name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    environment: pypi
    name: Build and attest
    runs-on: ubuntu-24.04
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
    - name: Repository checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python3 -m venv venv
        . ./venv/bin/activate
        ./venv/bin/pip install --require-virtualenv --upgrade pip tox

    - name: Build and verify
      run: |
        . ./venv/bin/activate
        tox -e release

    - name: Upload artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: dist
        path: dist/
        if-no-files-found: error

    - name: Attest build provenance
      uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0
      with:
        subject-path: dist/*
